import {CATALOG,CATEGORIES,CIVIC,GRID_KEYS,PRIMARY,capacity} from './catalog.js';
import {point} from './placement.js';
const N=128,CELL=16,HALF=1024,clamp=v=>Math.max(0,Math.min(1,v));
export class Coverage {
 constructor(ctx,onMutation=()=>{}){this.ctx=ctx;this.onMutation=onMutation;this.grids=Object.fromEntries(GRID_KEYS.map(k=>[k,{res:N,cell:CELL,data:new Float32Array(N*N),version:0}]));this.components=new Uint16Array(N*N);this.cellEdge=new Uint16Array(N*N).fill(65535);this.cellT=new Uint16Array(N*N);this.cellDist=new Uint16Array(N*N);this.nodes=[];this.edges=[];this.nodeIndex=new Map();this.edgeIndex=new Map();this.component=[];this.supply=[];this.demand=[];this.sources=[];this.version=0;this.gridMs=0;this.dirty=true;this.topologyDirty=true;this.job=null;this.warned=false;this.lastWind=NaN;this.lastSolar=NaN;this.lastRebuildStart=-Infinity;}
 topology(){const R=this.ctx.world.roads;this.nodes=[...R.nodes.values()];this.nodeIndex=new Map(this.nodes.map((n,i)=>[n.id,i]));this.edges=[];this.edgeIndex.clear();this.adj=this.nodes.map(()=>[]);for(const e of R.edges.values()){const a=this.nodeIndex.get(e.a),b=this.nodeIndex.get(e.b);if(a==null||b==null)continue;const i=this.edges.length;this.edgeIndex.set(e.id,i);this.edges.push(e);this.adj[a].push([b,e.length]);this.adj[b].push([a,e.length]);}this.component=new Uint16Array(this.nodes.length);let n=0;for(let i=0;i<this.nodes.length;i++){if(this.component[i])continue;const q=[i];this.component[i]=++n;for(let p=0;p<q.length;p++)for(const [j]of this.adj[q[p]])if(!this.component[j]){this.component[j]=n;q.push(j);}}this.componentCount=n;this.bins=new Map();for(const e of this.edges){const steps=Math.max(1,Math.ceil(e.length/4));let a=R.sample(e.id,0);for(let j=1;j<=steps;j++){const b=R.sample(e.id,j/steps),seg={ax:a.x,az:a.z,bx:b.x,bz:b.z,e,t0:(j-1)/steps,t1:j/steps};for(let z=Math.floor((Math.min(a.z,b.z)-60)/64);z<=Math.floor((Math.max(a.z,b.z)+60)/64);z++)for(let x=Math.floor((Math.min(a.x,b.x)-60)/64);x<=Math.floor((Math.max(a.x,b.x)+60)/64);x++){const key=x+','+z;if(!this.bins.has(key))this.bins.set(key,[]);this.bins.get(key).push(seg);}a=b;}}this.topologyDirty=false;}
 nearest(x,z){const list=this.bins?.get(Math.floor(x/64)+','+Math.floor(z/64));if(!list)return null;let best=null,d2=3600,t=0;for(const seg of list){const dx=seg.bx-seg.ax,dz=seg.bz-seg.az,q=clamp(((x-seg.ax)*dx+(z-seg.az)*dz)/(dx*dx+dz*dz||1)),xx=seg.ax+q*dx,zz=seg.az+q*dz,d=(xx-x)**2+(zz-z)**2;if(d<d2){d2=d;best=seg;t=seg.t0+(seg.t1-seg.t0)*q;}}return best?{edge:best.e,t,dist:Math.sqrt(d2)}:null;}
 componentAt(x,z){const r=this.ctx.world.roads.nearestEdge(x,z,60);return r?this.component[this.nodeIndex.get(r.edge.a)]||0:0;}
 *rebuild(){const started=performance.now();if(this.topologyDirty){this.topology();this.minCellX=this.minCellZ=N;this.maxCellX=this.maxCellZ=-1;for(let i=0;i<N*N;i++){const x=-HALF+(i%N+.5)*CELL,z=-HALF+(Math.floor(i/N)+.5)*CELL,r=this.nearest(x,z);this.components[i]=r?this.component[this.nodeIndex.get(r.edge.a)]||0:0;this.cellEdge[i]=r?this.edgeIndex.get(r.edge.id):-1;this.cellT[i]=r?Math.round(r.t*65535):0;this.cellDist[i]=r?Math.round(r.dist*1024):65535;if(r){this.minCellX=Math.min(this.minCellX,i%N);this.maxCellX=Math.max(this.maxCellX,i%N);this.minCellZ=Math.min(this.minCellZ,Math.floor(i/N));this.maxCellZ=Math.max(this.maxCellZ,Math.floor(i/N));}if((i&63)===63)yield;}}
 const W=this.ctx.world,S=W.services;for(const c of CATEGORIES){S.supply[c]=0;S.demand[c]=0;}this.supply=Array.from({length:this.componentCount+1},()=>({power:0,water:0,sewage:0,garbage:0}));this.demand=Array.from({length:this.componentCount+1},()=>({power:0,water:0,sewage:0,garbage:0}));this.kindSupply=Array.from({length:this.componentCount+1},()=>({}));this.sources=[];
 for(const item of S.items.values()){const f=CATALOG[item.kind].footprint,p=point(item,0,-f.d/2),hit=W.roads.nearestEdge(p.x,p.z,60),k=hit?this.component[this.nodeIndex.get(hit.edge.a)]:0;item.component=k;const source={item,k,hit};this.sources.push(source);for(const c of CATEGORIES){const v=capacity(item,c,this.ctx);S.supply[c]+=v;if(k)this.supply[k][c]+=v;}if(k&&PRIMARY[item.kind])this.kindSupply[k][item.kind]=(this.kindSupply[k][item.kind]||0)+capacity(item,PRIMARY[item.kind],this.ctx);}
 this.buildingCache=[];for(const b of W.buildings.items.values()){const k=this.componentAt(b.x,b.z);if(!k)continue;const power=b.type==='industrial'?3+2*b.level:1+b.level,need={power,water:.8*power,sewage:.8*power,garbage:(.5+.4*b.level)*(b.type==='industrial'?2:1)};for(const c of CATEGORIES){this.demand[k][c]+=need[c];S.demand[c]+=need[c];}this.buildingCache.push({b,k,hit:W.roads.nearestEdge(b.x,b.z,60)});}
 if(!this.nodes.length&&!this.warned){this.ctx.log.warn('No roads: service coverage uses the isolated-facility Euclidean fallback');this.warned=true;}
 for(const key of GRID_KEYS){const grid=this.grids[key],g=grid.data,isUtility=CATEGORIES.includes(key);let dist=null,sources=null;
 if(!isUtility&&this.nodes.length){dist=new Float64Array(this.nodes.length).fill(Infinity);sources=this.sources.filter(s=>s.item.kind===key&&s.hit);for(const s of sources){const e=s.hit.edge,a=this.nodeIndex.get(e.a),b=this.nodeIndex.get(e.b);dist[a]=Math.min(dist[a],s.hit.t*e.length+s.hit.dist);dist[b]=Math.min(dist[b],(1-s.hit.t)*e.length+s.hit.dist);}const seen=new Uint8Array(this.nodes.length);for(let step=0;step<this.nodes.length;step++){let u=-1,d=Infinity;for(let j=0;j<dist.length;j++)if(!seen[j]&&dist[j]<d){u=j;d=dist[j];}if(u<0)break;seen[u]=1;for(const[v,len]of this.adj[u])if(d+len<dist[v])dist[v]=d+len;}}
 // Zeroing native typed storage is cheap; only road-reachable bounds need the per-cell formula.
 g.fill(0);const minX=this.nodes.length?this.minCellX:0,minZ=this.nodes.length?this.minCellZ:0,span=this.nodes.length?Math.max(0,this.maxCellX-minX+1):N,rows=this.nodes.length?Math.max(0,this.maxCellZ-minZ+1):N;
 for(let cell=0;cell<span*rows;cell++){const i=(minZ+Math.floor(cell/span))*N+minX+cell%span,k=this.components[i];let v=0;if(!this.nodes.length){const x=-HALF+(i%N+.5)*CELL,z=-HALF+(Math.floor(i/N)+.5)*CELL;for(const s of this.sources){if(isUtility?capacity(s.item,key,this.ctx)>0:s.item.kind===key){const d=Math.hypot(x-s.item.x,z-s.item.z),r=isUtility?400:CATALOG[key].radius,t=clamp(1-d/r);v=Math.max(v,isUtility?(d<=r?1:0):t*t*(3-2*t));}}}else if(k&&isUtility){v=this.supply[k][key]>0?Math.min(1,this.supply[k][key]/Math.max(1e-6,this.demand[k][key])):0;}else if(k&&dist){const e=this.edges[this.cellEdge[i]],t=this.cellT[i]/65535;if(e){let d=Math.min(dist[this.nodeIndex.get(e.a)]+t*e.length,dist[this.nodeIndex.get(e.b)]+(1-t)*e.length)+this.cellDist[i]/1024;for(const s of sources)if(s.hit.edge.id===e.id)d=Math.min(d,Math.abs(t-s.hit.t)*e.length+s.hit.dist+this.cellDist[i]/1024);const v0=clamp(1-d/CATALOG[key].radius);v=v0*v0*(3-2*v0);}}g[i]=v;if((cell&255)===255)yield;}grid.version=this.version+1;}
 this.prepareCivicLoads();this.refreshLoads();

 this.version++;this.dirty=false;}
 prepareCivicLoads(){
  for(const source of this.sources){
   const {item,hit}=source, radius=CATALOG[item.kind].radius;
   if(radius===null)continue;
   source.covered=[];
   if(!this.nodes.length){for(const b of this.ctx.world.buildings.items.values())if(Math.hypot(b.x-item.x,b.z-item.z)<radius)source.covered.push(b);continue;}
   if(!hit)continue;
   const dist=new Float64Array(this.nodes.length).fill(Infinity),seen=new Uint8Array(this.nodes.length),edge=hit.edge;
   dist[this.nodeIndex.get(edge.a)]=hit.t*edge.length+hit.dist;
   dist[this.nodeIndex.get(edge.b)]=(1-hit.t)*edge.length+hit.dist;
   for(let step=0;step<this.nodes.length;step++){let u=-1,best=Infinity;for(let j=0;j<dist.length;j++)if(!seen[j]&&dist[j]<best){u=j;best=dist[j];}if(u<0||best>=radius)break;seen[u]=1;for(const[v,len]of this.adj[u])if(best+len<dist[v])dist[v]=best+len;}
   for(const rec of this.buildingCache){const bHit=rec.hit;if(!bHit)continue;const e=bHit.edge,t=bHit.t;let d=Math.min(dist[this.nodeIndex.get(e.a)]+t*e.length,dist[this.nodeIndex.get(e.b)]+(1-t)*e.length)+bHit.dist;if(e.id===edge.id)d=Math.min(d,Math.abs(t-hit.t)*e.length+hit.dist+bHit.dist);if(d<radius)source.covered.push(rec.b);}
  }
 }
 refreshLoads(){
  for(const source of this.sources){const {item,k}=source,primary=PRIMARY[item.kind];let load=0;
   if(primary)load=k?capacity(item,primary,this.ctx)*Math.min(1,this.demand[k][primary]/Math.max(1e-6,this.supply[k][primary])):0;
   else for(const b of source.covered||[])load+=Math.max(0,b.occupants||0);
   if(item.load!==load){item.load=load;this.onMutation(item.id);}
  }
 }
 flush(){if(!this.dirty&&!this.topologyDirty)return;const t=performance.now();this.lastRebuildStart=t;this.job=this.rebuild();while(!this.job.next().done){}this.job=null;this.gridMs=performance.now()-t;}
 update(){if(!this.dirty&&!this.topologyDirty&&!this.job)return;const start=performance.now();if(!this.job){if(start-this.lastRebuildStart<250)return;this.lastRebuildStart=start;this.job=this.rebuild();this.jobMs=0;}while(performance.now()-start<1.4){if(this.job.next().done){this.job=null;this.gridMs=this.jobMs+performance.now()-start;break;}}this.jobMs+=performance.now()-start;}
 refreshLive(){if(!this.sources.length||this.topologyDirty)return;const W=this.ctx.world,S=W.services;let changed=false;for(const c of CATEGORIES){const oldSupply=S.supply[c],oldDemand=S.demand[c];S.supply[c]=S.demand[c]=0;for(let k=0;k<this.supply.length;k++){this.supply[k][c]=0;this.demand[k][c]=0;}for(const {item,k}of this.sources){const v=capacity(item,c,this.ctx);S.supply[c]+=v;if(k)this.supply[k][c]+=v;}for(const {b,k}of this.buildingCache){const power=b.type==='industrial'?3+2*b.level:1+b.level,v=c==='power'?power:c==='garbage'?(.5+.4*b.level)*(b.type==='industrial'?2:1):power*.8;S.demand[c]+=v;this.demand[k][c]+=v;}if(Math.abs(oldSupply-S.supply[c])>.00001||Math.abs(oldDemand-S.demand[c])>.00001){changed=true;const g=this.grids[c].data;for(let i=0;i<g.length;i++){const k=this.components[i];g[i]=k&&this.supply[k][c]>0?Math.min(1,this.supply[k][c]/Math.max(1e-6,this.demand[k][c])):0;}}}for(const k of this.kindSupply)for(const key in k)k[key]=0;for(const {item,k}of this.sources){const c=PRIMARY[item.kind];if(c&&k){this.kindSupply[k][item.kind]=(this.kindSupply[k][item.kind]||0)+capacity(item,c,this.ctx);}}this.refreshLoads();if(changed){this.onMutation(null);this.version++;for(const c of CATEGORIES)this.grids[c].version=this.version;}}
 query(key,x,z){if(!Number.isFinite(x+z)||x<-1024||z<-1024||x>1024||z>1024)return 0;const grid=Object.hasOwn(this.grids,key)?this.grids[key]:null;let fx=(x+HALF)/CELL-.5,fz=(z+HALF)/CELL-.5;fx=Math.max(0,Math.min(127,fx));fz=Math.max(0,Math.min(127,fz));const ix=Math.min(126,Math.floor(fx)),iz=Math.min(126,Math.floor(fz)),a=fx-ix,b=fz-iz,i=iz*N+ix;
 if(grid){const g=grid.data;return (g[i]*(1-a)+g[i+1]*a)*(1-b)+(g[i+N]*(1-a)+g[i+N+1]*a)*b;}
 if(!Object.hasOwn(PRIMARY,key))return 0;if(!this.nodes.length){for(const s of this.sources)if(s.item.kind===key&&Math.hypot(x-s.item.x,z-s.item.z)<=400&&capacity(s.item,PRIMARY[key],this.ctx)>0)return 1;return 0;}const k=this.components[Math.round(fz)*N+Math.round(fx)],s=this.kindSupply?.[k]?.[key]||0;return s?Math.min(1,s/Math.max(1e-6,this.demand[k][PRIMARY[key]])):0;}
}
