import {CATALOG} from './catalog.js';
import {intersects} from './placement.js';
export const CAMERAS={utilities:{yaw:.7,pitch:.6,distance:380,target:[-195,28,-55]},plant_close:{yaw:.8,pitch:.27,distance:110,target:[-210,34,-65]},civic:{yaw:.6,pitch:.75,distance:260,target:[74,9,-49]},park:{yaw:.72,pitch:.22,distance:90,target:[-36,15,108]},coverage:{yaw:0,pitch:Math.PI/2-.01,distance:700,target:[0,0,0]},night_civic:{yaw:.75,pitch:.23,distance:140,target:[42,10,16]}};
export async function stage(ctx,api){const R=ctx.world.roads,T=ctx.world.terrain;const line=(x0,z0,x1,z1,type='street')=>{const a=R.addNode(x0,z0),b=R.addNode(x1,z1);return R.addEdge(a,b,type);};
 const plan=[['power_coal',-210,-68,Math.PI],['power_wind',-255,-180,0],['power_wind',-218,-180,0],['power_wind',-176,-180,0],['power_wind',-134,-180,0],['power_solar',-205,94,0],['landfill',-214,228,Math.PI],['incinerator',-128,-63,0],['clinic',20,20,Math.PI],['hospital',98,7,Math.PI],['school',28,-145,Math.PI],['high_school',108,-151,Math.PI],['university',188,-224,0],['police',20,-61,Math.PI],['fire',80,-62,Math.PI],['park_large',-24,110,0],['park_small',63,87,0],['plaza',121,88,0],['park_small',48,210,0],['park_small',114,210,0],['water_pump',195,-145,0],['sewage',246,-144,0]];
 const XS=[-280,-90,160,200,280],ZS=[-280,-210,-170,-106,-30,46,176,278];
 // Grade the fixed showcase sites through the public terrain API before placing roads or facilities.
 // This is stage construction, not a bypass in ordinary play placement. One continuous district
 // grade avoids deep channels between separate pads. Its outer eighty metres blend to terrain;
 // four facility crossfalls retain the sloped-pad test.
 if(T.setHeights&&T.heights){const res=T.resolution,cell=T.cellSize,half=ctx.world.size/2,values=T.heights.slice();for(let j=0;j<res;j++)for(let i=0;i<res;i++){const x=i*cell-half,z=j*cell-half;const outer=Math.max(0,Math.abs(x)-280,Math.abs(z)-280),u=Math.min(1,outer/80),districtBlend=1-u*u*(3-2*u);const bank=Math.max(0,Math.min(1,(x-145)/30))*Math.max(0,Math.min(1,(z+184)/24))*Math.max(0,Math.min(1,(-70-z)/35)),grade=15-13*bank;let value=values[j*res+i]*(1-districtBlend)+grade*districtBlend;for(let n=0;n<plan.length;n++){const[k,sx,sz,heading]=plan[n],f=CATALOG[k].footprint,dx=Math.abs(x-sx)-f.w/2,dz=Math.abs(z-sz)-f.d/2,d=Math.max(dx,dz),blend=Math.max(0,Math.min(1,k==='university'?(20-d)/20:(40-d)/34));if(!blend||!['power_coal','power_solar','landfill','university'].includes(k))continue;const slope=['power_coal','power_solar','landfill','university'].includes(k)?3.0*(x-sx)/f.w:0,target=(k==='university'?15:grade)+slope;value=value*(1-blend)+target*blend;}let roadDist=Infinity;for(let r=0;r<ZS.length;r++)for(let k=0;k<XS.length-1;k++){if(ZS[r]===-210&&k>0||ZS[r]===-170&&k<2)continue;const xx=Math.max(XS[k],Math.min(XS[k+1],x));roadDist=Math.min(roadDist,Math.hypot(x-xx,z-ZS[r]));}for(const xx of[-280,-90,280])roadDist=Math.min(roadDist,Math.hypot(x-xx,z-Math.max(ZS[0],Math.min(ZS.at(-1),z))));roadDist=Math.min(roadDist,Math.hypot(x-200,z-Math.max(-30,Math.min(278,z))));const roadBlend=Math.max(0,Math.min(1,(32-roadDist)/18));value=value*(1-roadBlend)+grade*roadBlend;const canalDistance=Math.max(Math.abs(x-218)-1,Math.abs(z+140)-15),canalBlend=Math.max(0,Math.min(1,(6-canalDistance)/6));value=value*(1-canalBlend)+(T.seaLevel-1)*canalBlend;values[j*res+i]=value;}T.setHeights(0,0,res-1,res-1,values,{restore:true});}

 // Explicit district roads connect at shared nodes, never merely at crossing geometry.

 for(let j=0;j<ZS.length;j++)for(let i=0;i<XS.length-1;i++){if(ZS[j]===-210&&i>0)continue;if(ZS[j]===-170&&i<2)continue;line(XS[i],ZS[j],XS[i+1],ZS[j],ZS[j]===46?'avenue':'street');}
 for(const x of[-280,-90,200,280])for(let j=0;j<ZS.length-1;j++){if(x===200&&ZS[j]<-30)continue;line(x,ZS[j],x,ZS[j+1]);}
 // Complete middle junction nodes at x=160 without a north-south street through the civic campuses.
 ctx.modules.roads.rebuild({preserveTerrain:true});ctx.modules.zoning.refresh();

 const failures=[];for(const [kind,x,z,h]of plan){const id=api.place(kind,x,z,h);if(id===null)failures.push({kind,x,z,result:api.validate(kind,x,z,h)});}ctx.log.info('service staging '+api.count()+'; rejected '+JSON.stringify(failures));
 // Public zoning painting creates authoritative lots; omit all service pads before spawning demand.
 ctx.modules.zoning.bulk(()=>{for(let z=-252;z<=252;z+=8)for(let x=-252;x<=252;x+=8){let hit=false;for(const [kind,sx,sz,h]of plan)if(intersects({x,z,heading:0,footprint:{w:12,d:12}},{kind,x:sx,z:sz,heading:h,footprint:CATALOG[kind].footprint})){hit=true;break;}if(!hit)ctx.modules.zoning.paint(x,z,5,'residential','low');}});ctx.modules.zoning.refresh();ctx.modules.buildings.spawnFreeLots(160);ctx.modules.zoning.setOverlayVisible(false);for(const [k,v]of Object.entries(CAMERAS))ctx.camera.registerPreset(k,v);api.flush();}
