import{chromium}from'playwright';import fs from'node:fs';
const dir='shots/democity/rdev2',write=(n,v)=>fs.writeFileSync(`${dir}/${n}.json`,JSON.stringify(v,null,2));
const browser=await chromium.launch({headless:true,executablePath:process.env.SIM_CHROME,args:['--use-angle=metal','--ignore-gpu-blocklist','--no-sandbox']});
const page=await browser.newPage({viewport:{width:1920,height:1080}});const browserErrors=[];await page.route('**/@vite/client',r=>r.fulfill({body:''}));page.on('pageerror',e=>browserErrors.push(String(e)));
async function open(seed=1337,extra=''){await page.goto(`http://127.0.0.1:5174/?showcase=democity&headless=1&time=12&camera=aerial&speed=0&seed=${seed}${extra}`);await page.waitForFunction(()=>window.__sim?.ready,null,{timeout:240000});await page.waitForTimeout(1500);}
async function census(){return page.evaluate(()=>{
 const s=window.__sim,w=s.world,a=s.registry.apis,d=a.democity,T=w.terrain,B=[...w.buildings.items.values()],P=[...w.props.items.values()],E=[...w.roads.edges.values()],D=d.plan(),res=B.filter(b=>b.type==='residential');
 const near=(p,q,r)=>Math.hypot(p.x-q.x,p.z-q.z)<=r, mean=x=>x.length?x.reduce((a,b)=>a+b,0)/x.length:null,med=x=>{x.sort((a,b)=>a-b);return x.length?(x[(x.length-1)>>1]+x[x.length>>1])/2:null;};
 const centre=D.districts.find(q=>q.kind==='downtown');
 const rings=Array.from({length:5},(_,i)=>{const bs=B.filter(b=>Math.floor(Math.hypot(b.x-centre.x,b.z-centre.z)/150)===i);return {n:bs.length,median:med(bs.map(b=>b.height))};});
 const subsets=Object.fromEntries(['industry','suburb','downtown'].map(k=>[k,B.filter(b=>d.districtAt(b.x,b.z)?.kind===k)]));
 const grain=Object.fromEntries(Object.entries(subsets).map(([k,bs])=>[k,{n:bs.length,area:mean(bs.map(b=>b.footprint.w*b.footprint.d)),spacing:mean(bs.map(b=>Math.min(...bs.filter(v=>v.id!==b.id).map(v=>Math.hypot(v.x-b.x,v.z-b.z)))))}]));
 const sb=subsets.suburb.filter(b=>b.type==='residential'&&b.density==='low');
 const treesIn=b=>P.filter(p=>p.kind.startsWith('tree_')&&(()=>{const lot=w.zones.lots.get(b.lotId)||b.lot,c=Math.cos(lot.heading),sn=Math.sin(lot.heading),dx=p.x-lot.x,dz=p.z-lot.z;return Math.abs(dx*c+dz*sn)<=lot.w/2&&Math.abs(-dx*sn+dz*c)<=lot.d/2;})()).length;
 const duplicate=[];for(let i=0;i<sb.length;i++)for(let j=i+1;j<sb.length;j++){const b=sb[i],v=sb[j];if(near(b,v,25)&&Math.abs(b.footprint.w-v.footprint.w)<=1&&Math.abs(b.footprint.d-v.footprint.d)<=1&&b.plan.roofTile===v.plan.roofTile)duplicate.push([b.id,v.id]);}
 const suburb={n:sb.length,pockets:[...new Set(sb.map(b=>d.districtAt(b.x,b.z)?.id))],drivewayHedge:sb.filter(b=>b.plan.driveway===true&&(b.plan.hedge||b.plan.fence)).length,twoGardenTrees:sb.filter(b=>treesIn(b)>=2).length,roofTiles:[...new Set(sb.map(b=>b.plan.roofTile))],styles:[...new Set(sb.map(b=>b.styleId))],duplicate};
 const cv=(k,b)=>w.services.coverage(k,b.x,b.z);const coverage={residential:res.length,power:res.filter(b=>cv('power',b)>0).length,water:res.filter(b=>cv('water',b)>0).length,both:res.filter(b=>cv('power',b)>0&&cv('water',b)>0).length,health:res.filter(b=>cv('clinic',b)+cv('hospital',b)>0).length,education:res.filter(b=>cv('school',b)+cv('high_school',b)+cv('university',b)>0).length,healthAndEducation:res.filter(b=>cv('clinic',b)+cv('hospital',b)>0&&cv('school',b)+cv('high_school',b)+cv('university',b)>0).length,supply:w.services.supply,demand:w.services.demand};
 const corner=(b)=>{const c=Math.cos(b.heading||0),sn=Math.sin(b.heading||0),h=[];for(const u of[-.5,.5])for(const v of[-.5,.5])h.push(T.getHeight(b.x+u*b.footprint.w*c-v*b.footprint.d*sn,b.z+u*b.footprint.w*sn+v*b.footprint.d*c));return {id:b.id,base:b.y,groundMax:Math.max(...h),gap:b.y-Math.max(...h),groundMin:Math.min(...h)};};
 // Deterministic permutation, independent of insertion order; exactly 200 sampled buildings.
 const ranked=B.map(b=>({b,key:((b.id*2654435761)>>>0)})).sort((a,b)=>a.key-b.key).slice(0,200).map(v=>corner(v.b));
 const landmarks=D.landmarks.map(l=>corner({...l,footprint:{w:l.w,d:l.d}}));
 const park=D.districts.find(q=>q.kind==='park'),inside=(p,r)=>Math.abs(p.x-r.x)<=r.w/2&&Math.abs(p.z-r.z)<=r.d/2;
 const parkProps=P.filter(p=>inside(p,park)),pt=parkProps.filter(p=>p.kind.startsWith('tree_'));const parkRepeated=[];for(let i=0;i<pt.length;i++)for(let j=i+1;j<pt.length;j++){const a=pt[i],b=pt[j],delta=Math.abs(Math.atan2(Math.sin(a.heading-b.heading),Math.cos(a.heading-b.heading)));if(near(a,b,8)&&delta<=5*Math.PI/180&&Math.abs(a.scale-b.scale)<=.03*Math.max(a.scale,b.scale))parkRepeated.push([a.id,b.id]);}
 const built=new Set(),put=(x,z)=>built.add(`${Math.floor(x/64)},${Math.floor(z/64)}`);for(const e of E)for(let i=0;i<=Math.ceil(e.length/4);i++){const p=w.roads.sample(e.id,i/Math.ceil(e.length/4));if(p)put(p.x,p.z);}for(const l of w.zones.lots.values())put(l.x,l.z);for(const l of D.landmarks)put(l.x,l.z);
 const highway=E.filter(e=>e.type==='highway'),curves=[];for(const e of highway){let prev=null,m=0;const count=Math.ceil(e.length/4);for(let i=0;i<=count;i++){const p=w.roads.sample(e.id,i/count);if(prev){const ang=Math.abs(Math.atan2(prev.tangent.x*p.tangent.z-prev.tangent.z*p.tangent.x,prev.tangent.x*p.tangent.x+prev.tangent.z*p.tangent.z))*180/Math.PI,dist=Math.hypot(p.x-prev.x,p.z-prev.z);if(dist)m=Math.max(m,ang/dist);}prev=p;}curves.push({id:e.id,length:e.length,maxDegreesPerM:m,a:w.roads.nodes.get(e.a),b:w.roads.nodes.get(e.b)});}
 const bridges=D.corridors.bridges.map(id=>{const e=w.roads.edges.get(id);return {id,type:e?.type,bridge:e?.bridge,samples:Array.from({length:40},(_,i)=>{const p=w.roads.sample(id,i/39);return {...p,terrain:T.getHeight(p.x,p.z),water:T.isWater(p.x,p.z),sea:T.seaLevel};})};});
 const streetNear=w.roads.nearestEdge(40,40,40),stBuildings=B.filter(b=>near(b,{x:40,z:40},45)),sp=streetNear?.point?.tangent||w.roads.sample(streetNear.edge.id,streetNear.t).tangent;
 const districtPoints=Array.from({length:20},(_,i)=>{const q=D.districts[i%D.districts.length],x=q.x+(i>=9?q.w*.24:0),z=q.z+(i>=9?q.d*.21:0);return {x,z,result:d.districtAt(x,z),containing:D.districts.filter(v=>inside({x,z},v)).map(v=>v.id)};});
 const inds=subsets.industry.filter(b=>b.type==='industrial');const ind=D.districts.find(x=>x.kind==='industry');
 const cranes=D.landmarks.filter(l=>l.kind==='crane').map(l=>{let distance=Infinity;for(let angle=0;angle<360;angle+=5)for(let r=0;r<=80;r+=2)if(T.isWater(l.x+Math.sin(angle*Math.PI/180)*r,l.z+Math.cos(angle*Math.PI/180)*r)){distance=Math.min(distance,r);break;}return {id:l.id,waterWithin80:Number.isFinite(distance),sampleDistance:distance};});
 const landValue=D.districts.map(q=>({id:q.id,value:a.simulation.landValueAt(q.x,q.z),pollution:a.simulation.pollutionAt(q.x,q.z)}));
 return {api:Object.fromEntries(['plan','districtAt','stats','fallbacks','tour','startTour','stopTour','gotoStop','tourState','restage','cropRects','serialize','deserialize'].map(k=>[k,typeof d[k]])),stats:d.stats(),plan:D,tour:d.tour(),tourState:d.tourState(),worldCounts:{nodes:w.roads.nodes.size,edges:E.length,lots:w.zones.lots.size,buildings:B.length,props:P.length},centroids:B.map(b=>[b.id,b.x,b.z]),rings,grain,suburb,coverage,seating:{buildings:ranked,landmarks},park:{area:park.area,trees:pt.length,kinds:[...new Set(pt.map(p=>p.kind))],lamps:parkProps.filter(p=>p.kind==='streetlamp').length,repeatPairs:parkRepeated,lots:[...w.zones.lots.values()].filter(l=>inside(l,park)).length},built:{cells:built.size,km2:built.size*4096/1e6},highway:curves,ramps:E.filter(e=>e.type==='ramp').map(e=>({id:e.id,a:e.a,b:e.b,oneWay:e.oneWay,lanes:e.lanes})),bridges,cameraCounts:{tallOrigin:B.filter(b=>b.height>60&&near(b,{x:0,z:0},260)).length,streetDistance:streetNear?.dist,streetBuildings:stBuildings.map(b=>({id:b.id,side:Math.sign((b.x-40)*sp.z-(b.z-40)*sp.x)})),closeup:B.filter(b=>near(b,{x:20,z:20},80)).length,nightTowers:B.filter(b=>b.height>40&&near(b,{x:-40,z:60},120)).length},districtPoints,industry:{n:inds.length,cranes,edges:E.filter(e=>['street','gravel'].includes(e.type)&&inside(w.roads.sample(e.id,.5),ind)).length,distanceFromCentre:Math.hypot(ind.x-centre.x,ind.z-centre.z)},traffic:{vehicles:[...w.traffic.vehicles.values()].filter(v=>near(v,{x:40,z:40},150)).map(v=>({id:v.id,kind:v.kind})),pedestrians:[...w.traffic.pedestrians.values()].filter(v=>near(v,{x:40,z:40},150)).length},services:[...w.services.items.values()].map(v=>({id:v.id,kind:v.kind,x:v.x,z:v.z,roadDistance:w.roads.nearestEdge(v.x,v.z,60)?.dist??null})),lines:a.transit.lines(),vehicles:a.transit.vehicles(),economy:{population:w.economy.population,jobs:w.economy.jobs,money:w.economy.money,happiness:w.economy.happiness,demand:w.economy.demand,grids:!!w.economy.grids,net:w.economy.net,loans:w.economy.loans,taxRate:w.economy.taxRate},landValue,errors:s.errors.slice(),perf:s.stats()};
 });}
try{
 await open();write('probe',await census());
 const cityfill=await page.evaluate(async()=>{const s=window.__sim,w=s.world,d=s.registry.apis.democity,results={};for(const camera of ['aerial','skyline','night_street','night_downtown']){s.setCamera(camera);await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));let sky=0,water=0,ground=0,city=0,hard=0;const samples=[];for(let row=0;row<40;row++)for(let col=0;col<40;col++){const p=s.camera.screenToGround(-.975+col*.05,.975-row*.05);let kind;if(!p){sky++;kind='sky';}else if(w.terrain.isWater(p.x,p.z)){water++;kind='water';}else{ground++;const h=w.roads.isRoad(p.x,p.z)>0||!!w.zones.cellAt(p.x,p.z)||!!w.buildings.at(p.x,p.z),c=h||!!d.districtAt(p.x,p.z);hard+=+h;city+=+c;kind=h?'hard':c?'district':'open';}samples.push({row,col,kind});}results[camera]={sky,water,ground,city,hard,cityFraction:city/ground,hardFraction:hard/ground,samples};}return results;});write('cityfill',cityfill);
 const contracts=await page.evaluate(async()=>{const s=window.__sim,d=s.registry.apis.democity;const counts=()=>{const x=d.stats();return {roads:x.roads,zones:x.zones,buildings:x.buildings,services:x.services,transitLines:x.transitLines,transitStops:x.transitStops,own:x.own};};const out={baseline:counts()},saved=d.serialize();out.deserialize=[d.deserialize(saved),d.deserialize(saved)];out.afterDeserialize=counts();out.restages=[];for(let i=0;i<2;i++){await d.restage();out.restages.push(counts());}out.seed7=await d.restage({seed:7});out.seed7plan=d.plan();out.gotoInvalid=d.gotoStop(100);out.start=d.startTour({from:0,loop:false});out.startState=d.tourState();d.stopTour();out.stopState=d.tourState();out.errors=s.errors.slice();return out;});write('census-contracts',contracts);
 await open(7);write('seed7-probe',await census());
 await open(1337,'&mode=play');write('play',await page.evaluate(()=>({stats:window.__sim.registry.apis.democity.stats(),errors:window.__sim.errors,perf:window.__sim.stats()})));
 await page.goto('http://127.0.0.1:5174/?showcase=democity&headless=1&time=12&camera=aerial&speed=1&seed=1337');await page.waitForFunction(()=>window.__sim?.ready,null,{timeout:240000});write('speed1',await page.evaluate(()=>({economy:{population:window.__sim.world.economy.population,jobs:window.__sim.world.economy.jobs,money:window.__sim.world.economy.money},stats:window.__sim.registry.apis.democity.stats(),errors:window.__sim.errors})));
 write('browser-errors',browserErrors);
}finally{await browser.close();}
