import{chromium}from'playwright';import fs from'node:fs';
const dir='shots/democity/rdev3',write=(n,v)=>fs.writeFileSync(`${dir}/${n}.json`,JSON.stringify(v,null,2));
const browser=await chromium.launch({headless:true,executablePath:process.env.SIM_CHROME,args:['--use-angle=metal','--ignore-gpu-blocklist','--no-sandbox']});
const page=await browser.newPage({viewport:{width:1920,height:1080}});const browserErrors=[];await page.route('**/@vite/client',r=>r.fulfill({body:''}));page.on('pageerror',e=>browserErrors.push(String(e)));
async function open(seed=1337,extra=''){await page.goto(`http://127.0.0.1:5174/?showcase=democity&headless=1&time=12&camera=aerial&speed=0&seed=${seed}${extra}`);await page.waitForFunction(()=>window.__sim?.ready,null,{timeout:240000});await page.waitForTimeout(1500);}
try{await open(); const cityfill=await page.evaluate(async()=>{const s=window.__sim,w=s.world,d=s.registry.apis.democity,results={};for(const camera of ['aerial','skyline','night_street','night_downtown']){s.setCamera(camera);await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));let sky=0,water=0,ground=0,city=0,hard=0;const samples=[];for(let row=0;row<40;row++)for(let col=0;col<40;col++){const p=s.camera.screenToGround(-.975+col*.05,.975-row*.05);let kind;if(!p){sky++;kind='sky';}else if(w.terrain.isWater(p.x,p.z)){water++;kind='water';}else{ground++;const h=w.roads.isRoad(p.x,p.z)>0||!!w.zones.cellAt(p.x,p.z)||!!w.buildings.at(p.x,p.z),c=h||!!d.districtAt(p.x,p.z);hard+=+h;city+=+c;kind=h?'hard':c?'district':'open';}samples.push({row,col,kind});}results[camera]={sky,water,ground,city,hard,cityFraction:city/ground,hardFraction:hard/ground,samples};}return results;});write('cityfill',cityfill);

 write('park-species',await page.evaluate(()=>{const s=window.__sim,d=s.registry.apis.democity.plan().districts.find(d=>d.kind==='park'),p=[...s.world.props.items.values()].filter(p=>p.kind.startsWith('tree_')&&Math.abs(p.x-d.x)<=d.w/2&&Math.abs(p.z-d.z)<=d.d/2);return {n:p.length,kinds:[...new Set(p.map(p=>p.kind))],species:[...new Set(p.map(p=>p.species))]};}));
}finally{await browser.close();}
