import {chromium} from 'playwright';import fs from 'node:fs/promises';
const out='shots/democity/rdev3',browser=await chromium.launch({executablePath:process.env.SIM_CHROME||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--use-angle=metal','--use-gl=angle','--enable-webgl','--ignore-gpu-blocklist','--no-sandbox']});
const page=await browser.newPage({viewport:{width:1920,height:1080}}),errors=[];page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await page.route('**/@vite/client',r=>r.fulfill({status:200,contentType:'application/javascript',body:''}));
try{
 await page.goto(`${process.env.SIM_URL||'http://127.0.0.1:5174'}/?showcase=democity&time=12&camera=aerial&headless=1&speed=0`);await page.waitForFunction(()=>window.__sim?.ready,null,{timeout:240000});
 const read=()=>page.evaluate(()=>{const s=window.__sim,a=s.registry.apis,d=a.democity,w=s.world,bs=[...w.buildings.items.values()],p=d.plan(),median=v=>v.sort((a,b)=>a-b)[Math.floor(v.length/2)]??0;
  const buildings=bs.slice(0,200).map(b=>{const c=Math.cos(b.heading),sn=Math.sin(b.heading),pts=[];for(const x of[-b.footprint.w/2,b.footprint.w/2])for(const z of[-b.footprint.d/2,b.footprint.d/2])pts.push([b.x+c*x+sn*z,b.z+sn*x-c*z]);const hs=pts.map(q=>w.terrain.getHeight(...q));return {id:b.id,x:b.x,z:b.z,y:b.y,highest:Math.max(...hs),error:b.y-Math.max(...hs),water:pts.some(q=>w.terrain.isWater(...q))};});
  const landmarkSeats=p.landmarks.map(l=>{const hs=[];for(const a of[-.5,.5])for(const b of[-.5,.5])hs.push(w.terrain.getHeight(l.x+l.w*a,l.z+l.d*b));return {id:l.id,error:l.y-Math.max(...hs),water:w.terrain.isWater(l.x,l.z)};});
  const bridges=p.corridors.bridges.map(id=>{const e=w.roads.edges.get(id),pts=Array.from({length:40},(_,i)=>{const q=w.roads.sample(id,i/39);return {...q,water:w.terrain.isWater(q.x,q.z),ground:w.terrain.getHeight(q.x,q.z)};});return {id,type:e?.type,bridge:e?.bridge,pts};});
  const near=(x,z,r)=>bs.filter(b=>Math.hypot(b.x-x,b.z-z)<=r),street=near(40,40,45),traffic=[...w.traffic.vehicles.values()].filter(v=>Math.hypot(v.x-40,v.z-40)<=150),peds=[...w.traffic.pedestrians.values()].filter(v=>Math.hypot(v.x-40,v.z-40)<=150);
  const props=[...w.props.items.values()],park=p.districts.find(d=>d.kind==='park'),parkProps=props.filter(v=>Math.abs(v.x-park.x)<park.w/2&&Math.abs(v.z-park.z)<park.d/2),low=bs.filter(b=>b.type==='residential'&&b.density==='low');
  return {counts:{roads:w.roads.edges.size,nodes:w.roads.nodes.size,zones:w.zones.cells.size,lots:w.zones.lots.size,buildings:bs.length,services:w.services.items.size,props:props.length,lines:w.transit.lines.size,stops:w.transit.stops.size,landmarks:p.landmarks.length},centres:bs.map(b=>[b.id,b.x,b.z]),plan:p,stats:d.stats(),economy:{population:w.economy.population,jobs:w.economy.jobs,money:w.economy.money},geometry:s.stats().geometries,seating:{buildings,landmarks:landmarkSeats,ownedProps:0,requested100OwnedProps:'inapplicable:real props and traffic owners prohibit duplicates'},bridges,cameraAnchors:{streetRoadDistance:w.roads.nearestEdge(40,40,100)?.dist,street45:street.length,streetSideCounts:[street.filter(b=>b.x<40).length,street.filter(b=>b.x>40).length],closeup80:near(20,20,80).length,night120Above40:near(-40,60,120).filter(b=>b.height>40).length,vehicles150:traffic.length,vehicleKinds:[...new Set(traffic.map(v=>v.kind))],peds150:peds.length},park:{area:park.area,trees:parkProps.filter(v=>v.kind.startsWith('tree')).length,kinds:[...new Set(parkProps.map(v=>v.kind))],lots:[...w.zones.lots.values()].filter(l=>Math.abs(l.x-park.x)<park.w/2&&Math.abs(l.z-park.z)<park.d/2).length},suburb:{low:low.length,driveways:low.filter(b=>b.plan.driveway).length,medianArea:median(low.map(b=>b.footprint.w*b.footprint.d))},industrial:{n:bs.filter(b=>b.type==='industrial').length,medianArea:median(bs.filter(b=>b.type==='industrial').map(b=>b.footprint.w*b.footprint.d))},errors:s.errors};});
 const result={initial:await read(),events:[],gpu:[]};
 // Measure true owner calls across all engine passes, without scene-delta attribution.
 for(const preset of['aerial','overview','street','closeup','closeup_night']){
  await page.evaluate(p=>{window.__sim.clock.set(p==='closeup_night'?22:12);window.__sim.camera.apply(p==='closeup_night'?'closeup':p);},preset);await page.waitForTimeout(350);
  const q=await page.evaluate(async()=>{const s=window.__sim,r=s.engine.renderer,g=s.registry.get('democity').group,orig=r.renderBufferDirect,frames=[];let own={calls:0,triangles:0,mainCalls:0,otherCalls:0};
   r.renderBufferDirect=function(...args){let o=args[4],has=false;while(o){if(o===g){has=true;break;}o=o.parent;}const c=r.info.render.calls,t=r.info.render.triangles;const v=orig.apply(this,args);if(has){const n=r.info.render.calls-c;own.calls+=n;own.triangles+=r.info.render.triangles-t;if(args[0]===s.camera.camera)own.mainCalls+=n;else own.otherCalls+=n;}return v;};
   const offBefore=s.engine.onBeforeRender(()=>{own={calls:0,triangles:0,mainCalls:0,otherCalls:0};}),offAfter=s.engine.onAfterRender(()=>frames.push({...own}));
   try{const f=s.engine.stats.frames;while(s.engine.stats.frames-f<24)await new Promise(r=>setTimeout(r,30));return frames.slice(-20);}finally{offBefore();offAfter();r.renderBufferDirect=orig;}});result.gpu.push({preset,frames:q});
 }
 await page.evaluate(()=>window.__sim.clock.set(12));
 const ownSave=await page.evaluate(()=>window.__sim.registry.apis.democity.serialize());
 result.deserialize=[];for(let i=0;i<2;i++){result.deserialize.push({ok:await page.evaluate(d=>window.__sim.registry.apis.democity.deserialize(d),ownSave),state:await read()});}
 result.restage=[];for(let i=0;i<2;i++){await page.evaluate(()=>window.__sim.registry.apis.democity.restage());await page.waitForTimeout(200);result.restage.push(await read());}
 result.save=await page.evaluate(async()=>{const s=window.__sim;const saved=await s.save('democity-r3');return {committed:!!saved,loaded:await s.load('democity-r3')};});result.loaded=await read();
 await page.evaluate(()=>{const s=window.__sim;s.__tourEvents=[];s.events.on('democity:tour',p=>s.__tourEvents.push(p),'democity-contract-probe');});
 result.tour=await page.evaluate(()=>{const s=window.__sim,d=s.registry.apis.democity,before=d.tourState(),invalid=d.gotoStop(100),rows=d.tour().map((v,i)=>({i,ok:d.gotoStop(i),hour:s.world.time.hour,state:d.tourState(),target:s.camera.target.toArray()}));const started=d.startTour({from:0,loop:false});d.stopTour();return {before,invalid,rows,started,after:d.tourState(),events:s.__tourEvents};});
 await page.evaluate(()=>window.__sim.registry.apis.democity.restage({seed:7}));result.restage7=await read();
 // Same-session road visibility diff, with five complete settling frames between states.
 await page.evaluate(()=>window.__sim.registry.apis.democity.restage({seed:1337}));
 await page.evaluate(()=>{const s=window.__sim;s.clock.set(17.5);s.camera.apply('street');});await page.waitForTimeout(350);await page.evaluate(()=>window.__sim.freeze());await page.screenshot({path:`${out}/roadmask-on.png`});
 await page.evaluate(()=>{const s=window.__sim;s.registry.get('roads').group.visible=false;s.unfreeze();});await page.waitForFunction(()=>window.__sim.engine.stats.frames>0);await page.evaluate(async()=>{const s=window.__sim,f=s.engine.stats.frames;while(s.engine.stats.frames<f+5)await new Promise(r=>setTimeout(r,30));s.freeze();});await page.screenshot({path:`${out}/roadmask-off.png`});await page.evaluate(()=>window.__sim.registry.get('roads').group.visible=true);
 result.roadMaskSeed=1337;result.browserErrors=errors;await fs.writeFile(`${out}/contracts.json`,JSON.stringify(result,null,2));console.log(JSON.stringify({initial:result.initial.counts,restage:result.restage.map(q=>q.counts),restage7:result.restage7.counts,save:result.save,errors},null,2));
}catch(e){await fs.writeFile(`${out}/contracts-failure.json`,JSON.stringify({error:String(e),errors},null,2));throw e;}finally{await browser.close();}
