import {chromium} from 'playwright';import fs from 'node:fs/promises';
const out=process.argv[2]||'shots/democity/rdev1/probe.json',seed=Number(process.argv[3]||1337);
const browser=await chromium.launch({executablePath:process.env.SIM_CHROME||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--use-angle=metal','--use-gl=angle','--enable-webgl','--ignore-gpu-blocklist','--no-sandbox']});
const page=await browser.newPage({viewport:{width:1920,height:1080}}),errors=[];page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await page.route('**/@vite/client',r=>r.fulfill({status:200,contentType:'application/javascript',body:''}));
try{await page.goto(`${process.env.SIM_URL||'http://127.0.0.1:5174'}/?showcase=democity&seed=${seed}&time=12&camera=aerial&headless=1&speed=0`);await page.waitForFunction(()=>window.__sim?.ready,null,{timeout:240000});await page.waitForTimeout(500);
 const result=await page.evaluate(()=>{const s=window.__sim,w=s.world,a=s.registry.apis,d=a.democity,p=d.plan(),bs=[...w.buildings.items.values()],median=v=>{v.sort((a,b)=>a-b);return v[Math.floor(v.length/2)]??0;};
  const grid={dry:0,districtOrBuilt:0,built:0,samples:[]};for(let j=0;j<40;j++)for(let i=0;i<40;i++){const q=s.camera.screenToGround((i+.5)/20-1,1-(j+.5)/20);if(!q||w.terrain.isWater(q.x,q.z))continue;const lot=a.zoning.lotAt(q.x,q.z),road=w.roads.isRoad(q.x,q.z),b=a.buildings.at(q.x,q.z),dist=d.districtAt(q.x,q.z);grid.dry++;if(lot||road||b)grid.built++;if(lot||road||b||dist)grid.districtOrBuilt++;grid.samples.push([q.x,q.z,!!dist,!!(lot||road||b)]);}
  const area=new Set();const claim=(x,z)=>{if(!w.terrain.isWater(x,z))area.add(`${Math.floor((x+1024)/64)},${Math.floor((z+1024)/64)}`);};for(const e of w.roads.edges.values())for(let n=0;n<=Math.ceil(e.length/24);n++){const q=w.roads.sample(e.id,n/Math.ceil(e.length/24));claim(q.x,q.z);}for(const b of w.zones.lots.values())claim(b.x,b.z);for(const l of p.landmarks)claim(l.x,l.z);
  const ring=Array.from({length:6},(_,i)=>{const v=bs.filter(b=>{const r=Math.hypot(b.x,b.z);return r>=150*i&&r<150*(i+1);});return {range:[150*i,150*(i+1)],n:v.length,medianHeight:median(v.map(b=>b.height))};});
  const utility={};for(const key of['power','water','clinic','school']){const homes=bs.filter(b=>b.type==='residential');utility[key]={nonzero:homes.filter(b=>a.services.coverage(key,b.x,b.z)>0).length/Math.max(1,homes.length),half:homes.filter(b=>a.services.coverage(key,b.x,b.z)>=.5).length/Math.max(1,homes.length)};}
  return {stats:d.stats(),plan:p,economy:{population:w.economy.population,jobs:w.economy.jobs,money:w.economy.money,happiness:w.economy.happiness,demand:w.economy.demand,net:w.economy.net},modules:s.registry.status(),render:s.stats(),cityfill:grid,areaKm2:area.size*4096/1e6,rings:ring,buildings:{count:bs.length,tall60:bs.filter(b=>Math.hypot(b.x,b.z)<260&&b.height>60).length,tallest:Math.max(0,...bs.map(b=>b.height)),types:Object.fromEntries(['residential','commercial','industrial','office'].map(k=>[k,bs.filter(b=>b.type===k).length])),lowHouses:bs.filter(b=>b.type==='residential'&&b.density==='low'&&b.level>=2).length},utilities:utility,props:a.props.stats(),traffic:a.traffic.stats(),services:a.services.stats(),transit:a.transit.stats?.(),errors:s.errors};});result.browserErrors=errors;await fs.writeFile(out,JSON.stringify(result,null,2));await fs.writeFile(out.replace(/[^/]+$/,'cityfill.json'),JSON.stringify(result.cityfill,null,2));console.log(JSON.stringify({...result,plan:undefined,cityfill:undefined,props:undefined,modules:undefined},null,2));
}finally{await browser.close();}
